# Generated by Django 3.2 on 2023-09-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='type',
            new_name='rate',
        ),
        migrations.RemoveField(
            model_name='record',
            name='amount',
        ),
        migrations.AddField(
            model_name='record',
            name='kinds',
            field=models.CharField(default=list, max_length=100),
            preserve_default=False,
        ),
    ]
